# Generated by Django 6.0.6 on 2026-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='item_imgs/'),
        ),
        migrations.AddField(
            model_name='stock_order',
            name='strength',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock_order',
            name='item',
            field=models.CharField(max_length=250),
        ),
    ]
