# Generated by Django 6.0.6 on 2026-08-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_order_order_items_delete_stock_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
    ]
