# Generated by Django 6.0.6 on 2026-08-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_bill_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SENDED', 'Sended'), ('PACKING', 'Packing'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received')]),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.bill_item')),
            ],
        ),
    ]
