# Generated by Django 6.0.6 on 2026-08-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_order_status_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='API.bill'),
        ),
        migrations.AlterField(
            model_name='bill_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_bills', to='API.item'),
        ),
    ]
