# Generated by Django 6.0.6 on 2026-08-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_inventory_brand_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='API.batch'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('ENJACTION', 'Enjection'), ('SYRUP', 'Syrup')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('item', 'strength')},
        ),
    ]
