# Generated by Django 6.0.6 on 2026-08-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_item_batch_alter_item_brand_alter_item_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.item'),
        ),
    ]
