# Generated by Django 6.0.6 on 2026-08-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_inventory_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PHARMACIST', 'Pharmacist'), ('SUPPLIER', 'Supplier')]),
        ),
    ]
